sma_user_homepage:
    pattern:  /
    defaults: { _controller: SMAUserBundle:Default:indexSekolah }

berita_sekolah:
    pattern:  /Berita/{id}
    defaults: { _controller: SMAUserBundle:Default:Berita }

profil_sekolah:
    pattern:  /ProfilSekolah/
    defaults: { _controller: SMAUserBundle:Default:ProfilSekolah }

sejarah_sekolah:
    pattern:  /SejarahSekolah/
    defaults: { _controller: SMAUserBundle:Default:SejarahSekolah }

visi_misi:
    pattern:  /VisiMisi/
    defaults: { _controller: SMAUserBundle:Default:VisiMisi }

teacher_home:
    pattern:  /TeacherHome/
    defaults: { _controller: SMAUserBundle:Default:TeacherHome }

buat_tugas:
    pattern:  /BuatTugas/
    defaults: { _controller: SMAUserBundle:Default:BuatTugas }

delete_tugas:
    pattern:  /BuatTugas/{id}
    defaults: { _controller: SMAUserBundle:Default:DeleteTugas }

list_jawaban:
    pattern:  /ListJawaban/
    defaults: { _controller: SMAUserBundle:Default:ListJawaban }

daftar_nilai:
    pattern:  /DaftarNilai/
    defaults: { _controller: SMAUserBundle:Default:DaftarNilai }

open_jawaban:
    pattern:  /OpenJawaban/{id}
    defaults: { _controller: SMAUserBundle:Default:OpenJawaban }

delete_jawaban:
    pattern:  /DeleteJawaban/{id}
    defaults: { _controller: SMAUserBundle:Default:DeleteJawaban }

teacher_profile:
    pattern:  /TeacherProfile/
    defaults: { _controller: SMAUserBundle:Default:TeacherProfile }

tedit_profile:
    pattern:  /TEditProfile/
    defaults: { _controller: SMAUserBundle:Default:TEditProfile }

student_home:
    pattern:  /StudentHome/
    defaults: { _controller: SMAUserBundle:Default:StudentHome }

list_tugas:
    pattern:  /ListTugas/
    defaults: { _controller: SMAUserBundle:Default:ListTugas }

list_nilai:
    pattern:  /ListNilai/
    defaults: { _controller: SMAUserBundle:Default:ListNilai }

open_tugas:
    pattern:  /OpenTugas/{id}
    defaults: { _controller: SMAUserBundle:Default:OpenTugas }

student_profile:
    pattern:  /StudentProfile/
    defaults: { _controller: SMAUserBundle:Default:StudentProfile }

sedit_profile:
    pattern:  /SEditProfile/
    defaults: { _controller: SMAUserBundle:Default:SEditProfile }

wait_page:
    pattern:  /Checking/
    defaults: { _controller: SMAUserBundle:Default:WaitPage }