parameters:
#    sma_user.example.class: SMA\UserBundle\Example

services:
#    sma_user.example:
#        class: %sma_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
